spring:
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mysql://mysql-3c05628f-satyapal06-1224.f.aivencloud.com:20828/defaultdb?sslmode=require
        name: MySQL Local Connection
        username: avnadmin
        password: AVNS_GTqLd4-hgBJi2L-gXAA
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        open-in-view: true
        factory-class: org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

jwt:
    header: Authorization
    secret: SpringBootSecretKey
    expiration: 300

server:
    port: 8080

debug: true

email:
  host: smtp.gmail.com
  port: 587
  username: satyapal06@gmail.com
  password: mrms ioxj ojon rcuu
  debug: true
